### ISSUE TITLE
Issues in Plotting Pressure Contour in zoomable maps; Notebook Ref: Adaptive Contouring in Fragment Shaders

### ISSUE THREAD

**Issue by nzahasan** [rreusser/sketches#30]
First of all thanks for sharing your awesome notebooks! I  have learned a lot reading them; 

I was trying use your your approach to generate pressure contour over a map from a png texture; currently I am following these steps
- encoding pressure data on R band of a png file
- load and visualize the png file with deck.gl's bitmaplayer
- modify frag shader of bitmaplayer to generate contour with your approach

currently the method somewhat works!; main issues is 

1. I am seeing noises at low zoom level
<img width="1438" alt="Screenshot 2024-12-09 at 11 10 21 PM" src="https://github.com/user-attachments/assets/0a238ea0-532f-4e8e-a22f-a0827436b835">

2. At high zoom level the lines are fading away or being fragmented into multiple lines
<img width="1438" alt="Screenshot 2024-12-09 at 11 12 15 PM" src="https://github.com/user-attachments/assets/f74b8d70-d05f-49be-9df8-e2c407cd3da1">

any suggestions  to solve these will be extremely  helpful!

I am attaching a workable version here for your reference
[contour-sample.zip](https://github.com/user-attachments/files/18065267/contour-sample.zip)

**Comment by rreusser** [comment]
Hi, @nzahasan. I've been away from the computer for a few days, but I'm taking a look now. For a start, here's a modification which improves the quality of simple contours using cubic spline interpolation. Although it's possible to perform bicubic sampling from linear sampling, I've used nearest sampling and texelFetch. Both techniques are described in this notebook: https://observablehq.com/@rreusser/bicubic-texture-interpolation-using-linear-filtering

The particular thing I think is going on is that standard derivatives may simply return zeros when the data comes from an image with discrete levels. If two adjacent pixels are quantized to the same PNG color level, then the derivative is just zero and doesn't locally represent the smooth gradations in a manner necessary to do some of these pixel effects.

This is the reason that bicubic interpolation can add a little more smoothness to the data. Basically, it pulls in sixteen pixels instead of four, so that it's more likely they will _all_ be exactly idential. You can see cubic interpolation (red) in this notebook: https://observablehq.com/@rreusser/cubic-basis-vs-hermite-interpolation. Note that although it's simple to implement, it may slightly undershoot the data.

The code below uses these techniques to draw simple contours. I've additionally modified a couple of the functions to use  modern GLSL features like texelFetch and textureSize.

```glsl
float grid (float parameter, float width, float feather) {
  float w1 = width - feather * 0.5;
  float d = length(vec2(dFdx(parameter), dFdy(parameter)));
  float looped = 0.5 - abs(mod(parameter, 1.0) - 0.5);
  return smoothstep(d * (w1 + feather), d * w1, looped);
}

vec4 cubic (float v) {
  vec4 n = vec4(1.0, 2.0, 3.0, 4.0) - v;
  vec4 s = n * n * n;
  float x = s.x;
  float y = s.y - 4.0 * s.x;
  float z = s.z - 4.0 * s.y + 6.0 * s.x;
  float w = 6.0 - x - y - z;
  return vec4(x, y, z, w) * (1.0 / 6.0);
}

vec4 bicubicX(sampler2D sampler, float xOff, vec4 xcub, vec2 uv) {
  vec2 size = vec2(textureSize(sampler, 0));
  return mat4(
    texelFetch(sampler, ivec2(mod(vec2(uv.x - xOff, uv.y) * size, size)), 0),
    texelFetch(sampler, ivec2(mod(uv * size, size)), 0),
    texelFetch(sampler, ivec2(mod(vec2(uv.x + xOff, uv.y) * size, size)), 0),
    texelFetch(sampler, ivec2(mod(vec2(uv.x + 2.0 * xOff, uv.y) * size, size)), 0)
  ) * xcub;
}

vec4 textureBicubicFromNearest(sampler2D sampler, vec2 texCoord) {
  vec2 size = vec2(textureSize(sampler, 0));
  vec2 invRes = 1.0 / size;
  texCoord = texCoord * size - 0.5;
  vec2 xy = fract(texCoord);
  texCoord = invRes * (texCoord - xy + 0.5);
  vec4 xcub = cubic(xy.x);
  return mat4(
    bicubicX(sampler, invRes.x, xcub, vec2(texCoord.x, texCoord.y - invRes.y)),
    bicubicX(sampler, invRes.x, xcub, texCoord),
    bicubicX(sampler, invRes.x, xcub, vec2(texCoord.x, texCoord.y + invRes.y)),
    bicubicX(sampler, invRes.x, xcub, vec2(texCoord.x, texCoord.y + 2.0 * invRes.y))
  ) * cubic(xy.y);
}

void main(void) {
  float a = dFdx(2.0);
  vec2 uv = vTexCoord;
  if (coordinateConversion < -0.5) {
    vec2 lnglat = mercator_to_lnglat(vTexPos);
    uv = getUV(lnglat);
  } else if (coordinateConversion > 0.5) {
    vec2 commonPos = lnglat_to_mercator(vTexPos);
    uv = getUV(commonPos);
  }
    
  vec4 bitmapColor = textureBicubicFromNearest(bitmapTexture, uv);

  const float CONTOUR_SPACING = 0.1;
  float contours = grid(length(bitmapColor.rg) / CONTOUR_SPACING, 1.0, 1.0);

  gl_FragColor = vec4(vec3(1.0), contours * 0.5);

  geometry.uv = uv;
  DECKGL_FILTER_COLOR(gl_FragColor, geometry);
}
```

The result is slightly cleaner contours, although if you zoom far enough in or out, you may still encounter issues due to zeros in the derivatives.

<img width="892" alt="Screenshot 2024-12-11 at 18 44 50" src="https://github.com/user-attachments/assets/dae48170-61cc-4ba5-aab3-036908860c25" />

Here's a second modification to just the main function which adds two levels of contours:

```glsl
void main(void) {
  float a = dFdx(2.0);
  vec2 uv = vTexCoord;
  if (coordinateConversion < -0.5) {
    vec2 lnglat = mercator_to_lnglat(vTexPos);
    uv = getUV(lnglat);
  } else if (coordinateConversion > 0.5) {
    vec2 commonPos = lnglat_to_mercator(vTexPos);
    uv = getUV(commonPos);
  }
    
  vec4 bitmapColor = textureBicubicFromNearest(bitmapTexture, uv);

  const float COARSE_CONTOUR_SPACING = 0.1;
  const float FINE_CONTOUR_SPACING = 0.02;

  float coarseContours = grid(length(bitmapColor.rg) / COARSE_CONTOUR_SPACING, 1.0, 1.0);
  float fineContours = grid(length(bitmapColor.rg) / FINE_CONTOUR_SPACING, 1.0, 1.0);

  float contours = max(fineContours * 0.15, coarseContours * 0.5);

  gl_FragColor = vec4(vec3(1.0), contours);

  geometry.uv = uv;
  DECKGL_FILTER_COLOR(gl_FragColor, geometry);
}
```

<img width="725" alt="Screenshot 2024-12-11 at 19 03 32" src="https://github.com/user-attachments/assets/a6a73a42-f3ea-4030-83bf-087325ebf1aa" />

I hope that's a reasonable start, and I'm intrigued enough that I'll take a look and see if I can adapt the function you originally pointed to to draw adaptively spaced contours.

**Comment by rreusser** [comment]
Although note that although bicubic interpolation may be _better_, it may still exhibit issues at high/low zoom in areas of low variation, e.g.:

<img width="233" alt="Screenshot 2024-12-11 at 19 13 40" src="https://github.com/user-attachments/assets/afb7bbf2-2ad7-448e-a0c0-9b3627ef6a88" />

**Comment by rreusser** [comment]
Oh, and finally, if the artifacts after a couple of these modifications are still unacceptable for your use, then there are a couple more strategies you might try:

1. first, you could encode data at higher precision using the red/green/blue channels, e.g. `red + 256 * blue + 256 * 256 * green`. Higher precision would help values from getting quantized to the same level, which is probably the main source of precision issues you're seeing.
2. If this sort of pixel effect places unacceptable constraints on precision and rendering, you might have to use something like `gdal_contour` to extract contours from the data and render them as vector features.

**Comment by nzahasan** [comment]
@rreusser many thanks for your response! 

I initially guessed that this may be an issue of image resolution and opted for using a finer resolution image to test my hypothesis, which actually worked! the fact that I can do interpolation in frag shader is just awesome and your approach is more than enough for my use case.

before this I have also experimented with using turf.js isolines to generate isolines on browser and then smoothing to smooth the sharp edges, this also worked but the performance was not satisfactory.  My fallback idea was to generate contour lines at server side and share as vector tiles to render on browser. Luckily! I found out your notebook which got me really intrigued! 

Again many thanks for your kind response!

**Comment by rreusser** [comment]
No problem, @nzahasan! Thank you very much for a clear, self-contained page that illustrates the issue. 🙇

**Comment by nzahasan** [comment]
Hi and sorry for bothering you again,

I was trying to set the contour linewidth through a uniform but its giving very unusual noise shown in the picture; if I set this manually this does not occur! do you have any idea why?

<img width="1426" alt="Screenshot 2024-12-22 at 10 31 04 PM" src="https://github.com/user-attachments/assets/1ec8e410-99b4-4e15-ae12-4b7f41d42e0d" />

**Comment by rreusser** [comment]
Hmm, no, I'm not sure. That seems unexpected. Maybe you could use the Spector.js extension to debug the shader? I couldn't immediately tell from the deck.gl source what the precision would be. Maybe the shader is using `precision mediump float` instead of highp?

https://chromewebstore.google.com/detail/spectorjs/denbgaamihkadbghdceggmchnflmhpmk?hl=en&pli=1

Have you definitely confirmed that this same data looks as expected when the value is not a uniform?

**Comment by nzahasan** [comment]
I have tried setting `precision highp float` its same! yes same data looks fine when line-width is hardcoded; I have attached a sample.
[contour-sample 2.zip](https://github.com/user-attachments/files/18224661/contour-sample.2.zip)

**Comment by rreusser** [comment]
Hmm, I'm able to reduce these artifacts by modifying the grid function to check for when the gradient of the parameter is zero, which I think is what's causing these artifacts. Then I just passed the `uv` coordinate along with it:

```
float grid (float parameter, float width, float feather, vec2 uv) {
  float w1 = width - feather * 0.5;
  float d = length(vec2(dFdx(parameter), dFdy(parameter)));
  float dv = length(vec2(dFdx(uv.x), dFdy(uv.y)));
  if (d/dv < 0.1) return 0.0;
  float looped = 0.5 - abs(mod(parameter, 1.0) - 0.5);
  return smoothstep(d * (w1 + feather), d * w1, looped);
}
```

Unfortunately I'm still seeing ghost contours at low zoom, and I'm not sure exactly what's causing that. If it's acceptable to you to fight these artifacts and achieve an acceptable result for this specific map, that's great, although I will note that fighting things like this is what led me to abandon this otherwise-remarkably-simple approach for a completely general offering in mapbox-gl.js.

**Comment by nzahasan** [comment]
Awesome solution! @rreusser more than enough!

I have noticed the ghost contours disappear gradually with increasing zoom, that means contour opacity for the same position is being changed, that means the length of derivative are being changed due to change of value at same position in different zoom level. So I am guessing its coming from interpolation!
